const { Sequelize } = require("sequelize");

module.exports = function (sequelize, DataTypes) {
    const RowsArrangement = sequelize.define('rows_arrangement', {
        rowId: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            autoIncrementIdentity: 'GENERATED BY DEFAULT AS IDENTITY',
        },
        noOfSeats: {
            type: DataTypes.INTEGER
        },
        department: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        createdOn: {
            type: DataTypes.DATE,
            defaultValue: Sequelize.NOW,
            allowNull: false,
        },
        createdBy: {
            type: DataTypes.STRING(10),
            defaultValue: "SYSTEM",
            allowNull: false,
        },
        modifiedOn: {
            type: DataTypes.DATE,
            allowNull: true,
        },
        modifiedBy: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        isActive: {
            type: DataTypes.BOOLEAN,
            defaultValue: true,
            allowNull: false,
        },
    }, {
        schema: 'config',
        tableName: 'rows_arrangement',
        timestamps: false,
        comment: 'Admin will fill the data from the UI for this table which will store the row arrangement structure which will be used for visualisation and other purposes.',
        underscored: true,
        freezeTableName: true,
        hasTrigger: true,
    })
    return RowsArrangement;
}