const { Sequelize } = require('sequelize');

module.exports = function (sequelize, DataTypes) {
    const User = sequelize.define('user_master', {
        userId: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            autoIncrementIdentity: 'GENERATED BY DEFAULT AS IDENTITY',
        }
    })
}